Added stratification to train/test split
bagherilab/emulation pull request #23
Opened 2023-03-29 19:51 UTC by jacob-evarts

2023-03-30 15:32 UTC, cainja requested changes

2023-03-30 15:32 UTC, cainja commented on src/config.py
> +    stratify = config["stratify"]
check for KeyError here, if you make it optional later on.

2023-03-30 15:32 UTC, cainja commented on src/conf/config.yaml
> +stratify: LAYOUT
I don't think it is possible to not specify this. Follow up comment below.

2023-03-30 21:38 UTC, jacob-evarts commented on src/conf/config.yaml
> +stratify: LAYOUT
apparently if you leave it blank it just sets it to None, so no need to check for a keyError either

2023-03-31 21:40 UTC, cainja approved these changes
good work

2023-04-03 18:47 UTC, merged